version: '3'
networks:
  default:
    external:
      name: traveler-dev
services:
  cable-mongo:
    image: "mongo:3.4"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootspass
      - MONGO_INITDB_DATABASE=cable
    command: --smallfiles
    volumes:
      # mapping for the db setup script
      - ./seed:/docker-entrypoint-initdb.d
      # mapping for the db location
      - ./data:/data/db
    ports:
      - "27018:27017"
  cable-mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8082:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=cable-mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootspass
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_BASICAUTH_USERNAME=cable
      - ME_CONFIG_BASICAUTH_PASSWORD=cablepass
    depends_on:
      - "cable-mongo"

